# Generated by Django 3.2.16 on 2022-12-14 20:40
from typing import Any, List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.CharField(max_length=250)),
                ("answer", models.CharField(max_length=250)),
            ],
        ),
    ]
