# Generated by Django 3.2.16 on 2022-12-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
